import { useEffect, useRef } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

interface Props { lat:number; lng:number; accuracy:number; locked:boolean; devicePosition?:boolean; landmark?:{lat:number;lng:number;name:string}|null; }
const TILE='https://mapapi.geodata.gov.hk/gs/api/v1.0.0/xyz/basemap/WGS84/{z}/{x}/{y}.png';
const LABEL='https://mapapi.geodata.gov.hk/gs/api/v1.0.0/xyz/label/hk/tc/WGS84/{z}/{x}/{y}.png';
export default function LocationMap({lat,lng,accuracy,locked,devicePosition=true,landmark}:Props){
 const host=useRef<HTMLDivElement>(null), map=useRef<L.Map|null>(null), marker=useRef<L.CircleMarker|null>(null), circle=useRef<L.Circle|null>(null), landmarkMarker=useRef<L.CircleMarker|null>(null), link=useRef<L.Polyline|null>(null);
 useEffect(()=>{if(!host.current||map.current)return;const m=L.map(host.current,{zoomControl:true,attributionControl:true}).setView([lat,lng],16);L.tileLayer(TILE,{minZoom:10,maxZoom:20,attribution:'Map from Lands Department'}).addTo(m);L.tileLayer(LABEL,{minZoom:10,maxZoom:20,pane:'overlayPane'}).addTo(m);map.current=m;setTimeout(()=>m.invalidateSize(),0);return()=>{m.remove();map.current=null}},[]);
 useEffect(()=>{const m=map.current;if(!m)return;const ll=L.latLng(lat,lng);if(!marker.current)marker.current=L.circleMarker(ll,{radius:devicePosition?8:10,color:'#fff',weight:3,fillColor:devicePosition?(locked?'#e9a23b':'#2078d4'):'#c53d35',fillOpacity:1}).bindTooltip(devicePosition?'裝置定位':'已確認地標',{permanent:!devicePosition,direction:'top'}).addTo(m);else marker.current.setLatLng(ll).setRadius(devicePosition?8:10).setStyle({fillColor:devicePosition?(locked?'#e9a23b':'#2078d4'):'#c53d35'}).bindTooltip(devicePosition?'裝置定位':'已確認地標',{permanent:!devicePosition,direction:'top'});if(!circle.current)circle.current=L.circle(ll,{radius:accuracy,color:'#2078d4',weight:1,fillOpacity:.12}).addTo(m);else circle.current.setLatLng(ll).setRadius(accuracy);if(landmark){const lm=L.latLng(landmark.lat,landmark.lng);if(!landmarkMarker.current)landmarkMarker.current=L.circleMarker(lm,{radius:10,color:'#fff',weight:3,fillColor:'#c53d35',fillOpacity:1}).addTo(m);landmarkMarker.current.setLatLng(lm).bindTooltip(`已確認：${landmark.name}`,{permanent:true,direction:'top'});if(!link.current)link.current=L.polyline([ll,lm],{color:'#c53d35',dashArray:'5 7',weight:2}).addTo(m);else link.current.setLatLngs([ll,lm]);m.fitBounds(L.latLngBounds([ll,lm]).pad(.35),{maxZoom:18});}else{landmarkMarker.current?.remove();landmarkMarker.current=null;link.current?.remove();link.current=null;m.panTo(ll)}},[lat,lng,accuracy,locked,devicePosition,landmark]);
 return <div className="location-map" ref={host} aria-label="目前位置地圖"/>;
}
